name: time_machine_cam
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  time_machine_config:
    path: ../time_machine_config
  time_machine_db:
    path: ../time_machine_db
  time_machine_net:
    path: ../time_machine_net
  time_machine_res:
    path: ../time_machine_res

  adaptive_action_sheet: ^2.0.4
  animated_transform: ^1.0.6
  ar_location_view: ^2.0.16
  cached_network_image: ^3.4.1
  camerawesome: ^2.4.0
  cross_file: any
  custom_image_crop: ^0.1.1
  flutter_cache_manager : ^3.4.1
  flutter_compass: ^0.8.1
  font_awesome_flutter: any
  geolocator: any
  go_router: any
  image: ^4.5.2
  image_picker: ^1.1.2
  intl: any
  native_device_orientation: ^2.0.3
  native_exif: ^0.6.2
  provider: ^6.1.2
  rxdart: ^0.28.0
  sensors_plus: any
  share_plus: ^10.1.3
  url_launcher: ^6.3.1
  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
